


MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=mazbaul011
MAIL_PASSWORD=tpjdktdynyrtgqjn
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS="mazbaul011@gmail.com"
MAIL_FROM_NAME="${APP_NAME}"